/**
 * Created by 7Summits on 2/12/18.
 */

/**
 * Shared constants used ONLY in test classes
 */
public with sharing class Dal_TestConstants {

    public static final string SSC_ALIAS = 'SSC';
    public static final string SSC_USERNAME = 'SSCUser@DalTile.com';
    public static final string SSC_EMAIL = 'SSCUser@DalTile.com';

    public static final string DISTRIBUTOR_ALIAS = 'Distrib';
    public static final string DISTRIBUTOR_USERNAME = 'DistributorUser@DalTile.com';
    public static final string DISTRIBUTOR_EMAIL = 'DistributorUser@DalTile.com';

    public static final string USER_SELECTED_LOCATION = '1234';
    public static final string USER_DIVISION = 'Div-Test';
    public static final string USER_ROLE = 'Test Role';

}