@isTest
private with sharing class Dal_Validate_Address_IntegerationTest {
    
    private static testMethod void Dal_Validate_Address()
    {
        new Dal_Validate_Address_Integeration.Response();
        new Dal_Validate_Address_Integeration.GetAddressValidation_ctxResponseBody();
        new Dal_Validate_Address_Integeration.ArrayOfPerformanceCounter();
        new Dal_Validate_Address_Integeration.Address();
        new Dal_Validate_Address_Integeration.GetAddressValidationResponseBody();
        new Dal_Validate_Address_Integeration.ServiceContext();
        new Dal_Validate_Address_Integeration.Request();
        new Dal_Validate_Address_Integeration.GetAddressValidation_ctxRequestBody();
        new Dal_Validate_Address_Integeration.PerformanceData();
        new Dal_Validate_Address_Integeration.GetAddressValidationRequestBody();
        new Dal_Validate_Address_Integeration.PerformanceCounter();
        new Dal_Validate_Address_Integeration.Result();        
    }
}