@isTest
private with sharing class Dal_ATP_Inventory_ControllerTest {
  private static testMethod void Dal_ATP_Inventory()
    {
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_TimePhasedResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_ByShade_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDate_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.ArrayOfResponseItem();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocationResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_TimePhased_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.ResponseItem();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_AvailabilityDateRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_TimePhased_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtNearbySSCS_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_TimePhased_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.ServiceContext();
        new Dal_ATP_Inventory_Controller.GetInventoryAtNearbySSCS_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.DocumentOptions();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.InventoryRequest();
        new Dal_ATP_Inventory_Controller.PerformanceCounter();
        new Dal_ATP_Inventory_Controller.GetInventoryAtNearbySSCSRequestBody();
        new Dal_ATP_Inventory_Controller.Destination();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_TimePhasedRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupplyRequestBody();
        new Dal_ATP_Inventory_Controller.PerformanceData();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_ByShadeRequestBody();
        new Dal_ATP_Inventory_Controller.InventoryResponse();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDateRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDate_PriceResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDate_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_TimePhased_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_AvailabilityDate_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDate_Price_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.RequestItem();        
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_ByShadeResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDate_PriceRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_ByShade_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_ctxRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtNearbySSCSResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_AvailabilityDateResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDateResponseBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocationRequestBody();       
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_ctxResponseBody(); 
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_TimePhasedRequestBody();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupplyResponseBody();
        new Dal_ATP_Inventory_Controller.ArrayOfPerformanceCounter();
        new Dal_ATP_Inventory_Controller.GetInventoryAtSourcesOfSupply_AvailabilityDate_Price_ctxRequestBody(); 
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_TimePhasedResponseBody();
        new Dal_ATP_Inventory_Controller.ArrayOfRequestItem();
        new Dal_ATP_Inventory_Controller.GetInventoryAtLocation_AvailabilityDate_ctxResponseBody();
        new Dal_ATP_Inventory_Controller.SupplyPlant();        
    }
}