public with sharing class Peak_TestConstants {
	public static final Integer HOW_MANY = 5;

	public static final String GUEST_ALIAS = 'Guest';
	public static final String GUEST_USERNAME = 'guestuser@peak.com';
	public static final String GUEST_EMAIL = 'guestuser@peak.com';

	public static final String STANDARD_ALIAS = 'Standard';
	public static final String STANDARD_USERNAME = 'standarduser@peak.com';
	public static final String STANDARD_EMAIL = 'standarduser@peak.com';

	public static final String LASTNAME = 'Testing';
	public static final String FIRSTNAME = 'Name';

	public static final String LOCALE = 'en_US';
	public static final String TIMEZONE = 'America/Los_Angeles';

	public static final String ENCODING = 'utf-8';

	public static final String ACCOUNT_NAME = 'Test Account';

	public static final String TEST_MESSAGE = 'Test message';

	public static final String TEST_URL = 'http://7summitsinc.com';
	public static final String TEST_DESCRIPTION = 'Donec ac dolor nec libero sagittis facilisis quis vel mauris. Curabitur eu dignissim augue. Sed ut consequat purus. Curabitur porta eget leo a molestie.';

	public static final String TEST_FILENAME = 'test.png';
	public static final String TEST_FILETYPE = 'image/png';

	public static final String TEST_GROUPNAME = 'Testing Group';

	public static final String TEST_GALLERYNAME = 'Testing Gallery';
	public static final String TEST_GALLERYENTRYNAME = 'Testing Gallery Entry';
	public static final Decimal TEST_GALLERYENTRYSORT1 = 1;
	public static final Decimal TEST_GALLERYENTRYSORT2 = 2;

	public static final Decimal AMOUNT = 500;
	public static final String FORECAST_CATEGORY_CLOSED = 'Closed';
	public static final String FORECAST_CATEGORY_COMMIT= 'Commit';
	public static final String STAGE_NAME = 'Sample Stage Name';
	public static final String OPP_NAME = 'Big Sale';

	public static final Date TODAY = System.today();

}